name: Spigotify
version: '${project.version}'
main: live.mufin.spigotify.Spigotify
api-version: 1.18
depend:
  - PlaceholderAPI
libraries:
  - com.squareup.okhttp3:okhttp:4.9.3
  - com.github.ben-manes.caffeine:caffeine:3.0.5

commands:
  setuser:
    aliases: su
    description: Sets your Last.fm user.
    permission: spigotify.setuser
    usage: /<command> <username>
  togglevisible:
    description: Toggles wether people can see your playing song or not.
    permission: spigotify.togglevisible
    usage: /<command>
  spigotify:
    description: Spigotify's main command.
    usage: /<command>